import raw from './dataFreshness.json';

// Generated by scripts/generate-data-freshness.mjs from git history — the date
// each category's product JSON last actually changed. Regenerate after editing
// product data:  node scripts/generate-data-freshness.mjs
//
// This is deliberately not the build timestamp. Restamping every page on every
// deploy teaches Google that the site's dateModified carries no information,
// which then devalues it on the pages where the data really did change.
const freshness = raw as Record<string, string>;

export function dataUpdatedAt(categorySlug: string): string | undefined {
  return freshness[categorySlug];
}

export function formatUpdated(iso: string | undefined): string | undefined {
  if (!iso) return undefined;
  const date = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(date.getTime())) return undefined;
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' });
}
